window:
  caption: "Hello World"
  resolution: &id001
    width: 640
    height: 480
  fullscreen: No

Shaders:
  vertex_shader:  "lib/v_shader.glsl"
  fragment_shader: "lib/f_shader.glsl"
  geom_shader: ""

Camera:
  eye: [0,0,2]
  target: [0,0,0]
  up: [0,1,0]
  fow: 55
  aspect_ratio: *id001
  far_plane: 100.0
  near_plane: 1
  mouse_speed: 2.5
  mouse_sensitivity: 0.1
  projection: 'perspective'

Light:
  position: [1.2, 1.0, 2.0]
  ambient:  [0.5, 0.5, 0.5]
  diffuse:  [0.5, 0.5, 0.5]
  specular: [1.0, 1.0, 1.0]


