window:
  caption: "Hello World"
  width: 640
  height: 480
  fullscreen: No
  resizeable: True

Shaders:
  vertex_shader:  "lib/v_shader.glsl"
  fragment_shader: "lib/f_shader.glsl"
  geom_shader: ""

Light:
  position: [1.2, 1.0, 2.0]
  ambient:  [0.8, 0.8, 0.8]
  diffuse:  [0.5, 0.5, 0.5]
  specular: [1.0, 1.0, 1.0]

Keyboard:
  forward: 'W'
  back: 'S'
  strafe_left: 'A'
  strafe_right: 'D'
  rotate_up: 'UP'
  rotate_down: 'DOWN'
  rotate_left: 'LEFT'
  rotate_right: 'RIGHT'
  quit: 'ESCAPE'
  toggle_fullscreen: 'P'

