window:
  caption: "Hello World"
  width: 640
  height: 480
  fullscreen: No

Shaders:
  vertex_shader:  "lib/v_shader.glsl"
  fragment_shader: "lib/f_shader.glsl"
  geom_shader: ""

Camera:
  eye: [0,0,-3]
  target: [0,0,0]
  up: [0,1,0]
  fow: 60
  aspect_ratio: '4/3'

